CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

CREATE TYPE public."offerapplicationstatus" AS ENUM (
    'ACCEPTED',
    'DENIED',
    'NEEDS_REVIEW',
    'UNSEEN');

CREATE TYPE public."utemroles" AS ENUM (
    'ROLE_ADMINISTRATOR',
    'ROLE_COMPANY',
    'ROLE_USER');

CREATE TYPE public."workmode" AS ENUM (
    'FLEXIBLE',
    'PRESENTIAL_ONLY',
    'REMOTE_ONLY');

CREATE TYPE public."worktype" AS ENUM (
    'FULL_TIME',
    'INTERNSHIP',
    'PART_TIME');

CREATE SEQUENCE public.app_users_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE public.bdt_offers_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE public.experience_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE public.offer_applications_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE public.offer_locations_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE TABLE public.companies
(
    created_at   timestamp(6) NOT NULL,
    updated_at   timestamp(6) NOT NULL,
    rut          varchar(12)  NOT NULL,
    fantasy_name varchar(255) NOT NULL,
    CONSTRAINT companies_pkey1 PRIMARY KEY (rut)
);

CREATE TABLE public.companies_backup
(
    digito_verificador varchar(1)   NOT NULL,
    rut                int4         NOT NULL,
    created_at         timestamp(6) NOT NULL,
    updated_at         timestamp(6) NOT NULL,
    fantasy_name       varchar(255) NOT NULL,
    CONSTRAINT companies_pkey PRIMARY KEY (rut)
);

CREATE TABLE public.offer_locations
(
    created_at     timestamp(6)                                                                                                             NOT NULL,
    id             int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    updated_at     timestamp(6)                                                                                                             NOT NULL,
    address        varchar(255)                                                                                                             NULL,
    address_number varchar(255)                                                                                                             NULL,
    city           varchar(255)                                                                                                             NOT NULL,
    district       varchar(255)                                                                                                             NOT NULL,
    region         varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT offer_locations_pkey PRIMARY KEY (id)
);

CREATE TABLE public.app_users
(
    created_at         timestamp(6)                                                                                                             NOT NULL,
    id                 int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    updated_at         timestamp(6)                                                                                                             NOT NULL,
    rut                varchar(10)                                                                                                              NOT NULL,
    associated_company varchar(12)                                                                                                              NULL,
    email              varchar(255)                                                                                                             NOT NULL,
    lastname           varchar(255)                                                                                                             NULL,
    "name"             varchar(255)                                                                                                             NOT NULL,
    "password"         varchar(255)                                                                                                             NOT NULL,
    "role"             public."utemroles"                                                                                                       NOT NULL,
    CONSTRAINT app_users_email_key UNIQUE (email),
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_rut_key UNIQUE (rut),
    CONSTRAINT fknyprwycfavxfshfa58tv0we7n FOREIGN KEY (associated_company) REFERENCES public.companies (rut)
);

CREATE TABLE public.bdt_offers
(
    salary            float8                                                                                                                   NOT NULL,
    created_at        timestamp(6)                                                                                                             NOT NULL,
    end_date          timestamp(6)                                                                                                             NOT NULL,
    id                int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    offer_author      int8                                                                                                                     NULL,
    offer_location    int8                                                                                                                     NOT NULL,
    start_date        timestamp(6)                                                                                                             NOT NULL,
    updated_at        timestamp(6)                                                                                                             NOT NULL,
    offer_description varchar(255)                                                                                                             NOT NULL,
    offer_name        varchar(255)                                                                                                             NOT NULL,
    work_mode         public."workmode"                                                                                                        NOT NULL,
    work_type         public."worktype"                                                                                                        NOT NULL,
    CONSTRAINT bdt_offers_pkey PRIMARY KEY (id),
    CONSTRAINT fkj30g8mhw49ddc6gcpo46yagbv FOREIGN KEY (offer_location) REFERENCES public.offer_locations (id),
    CONSTRAINT fkkuy7jt9gramvqnper4cb9cl38 FOREIGN KEY (offer_author) REFERENCES public.app_users (id)
);

CREATE TABLE public.experience
(
    app_user     int8                                                                                                                     NOT NULL,
    created_at   timestamp(6)                                                                                                             NOT NULL,
    end_date     timestamp(6)                                                                                                             NULL,
    id           int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    start_date   timestamp(6)                                                                                                             NOT NULL,
    updated_at   timestamp(6)                                                                                                             NOT NULL,
    company_name varchar(255)                                                                                                             NOT NULL,
    description  varchar(255)                                                                                                             NULL,
    title        varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT experience_pkey PRIMARY KEY (id),
    CONSTRAINT fk2uxaag389ieoqpqfpwwtg4ols FOREIGN KEY (app_user) REFERENCES public.app_users (id)
);

CREATE TABLE public.offer_applications
(
    appliant_user            int8                                                                                                                     NOT NULL,
    application_request_date timestamp(6)                                                                                                             NOT NULL,
    created_at               timestamp(6)                                                                                                             NOT NULL,
    id                       int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    offer                    int8                                                                                                                     NOT NULL,
    updated_at               timestamp(6)                                                                                                             NOT NULL,
    application_status       public."offerapplicationstatus"                                                                                          NOT NULL,
    CONSTRAINT offer_applications_pkey PRIMARY KEY (id),
    CONSTRAINT fkcgfrlxdfy09qcj3akq0w3upr3 FOREIGN KEY (offer) REFERENCES public.bdt_offers (id),
    CONSTRAINT fkjdxtir0u5405xi3w7d2hmp0xh FOREIGN KEY (appliant_user) REFERENCES public.app_users (id)
);

CREATE TABLE curriculums
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255),
    email           VARCHAR(255),
    phone_number    VARCHAR(255),
    address         VARCHAR(255),
    education       VARCHAR(255),
    experience      TEXT,
    skills          TEXT,
    certifications  VARCHAR(255),
    languages       VARCHAR(255),
    referrals       TEXT,
    CONSTRAINT pk_curriculums PRIMARY KEY (id)
);

ALTER TABLE curriculums
    ADD CONSTRAINT uc_curriculums_user UNIQUE (user_id);

ALTER TABLE curriculums
    ADD CONSTRAINT FK_CURRICULUMS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);


CREATE OR REPLACE FUNCTION public.format_rut(numeric_rut integer, dv text)
    RETURNS text
    LANGUAGE plpgsql
AS
$function$
DECLARE
    rut_str   TEXT := numeric_rut::TEXT;
    formatted TEXT;
BEGIN
    -- Agrega los puntos desde el final
    IF LENGTH(rut_str) = 8 THEN
        formatted := SUBSTRING(rut_str, 1, 2) || '.' ||
                     SUBSTRING(rut_str, 3, 3) || '.' ||
                     SUBSTRING(rut_str, 6, 3);
    ELSIF LENGTH(rut_str) = 7 THEN
        formatted := SUBSTRING(rut_str, 1, 1) || '.' ||
                     SUBSTRING(rut_str, 2, 3) || '.' ||
                     SUBSTRING(rut_str, 5, 3);
    ELSE
        formatted := rut_str; -- fallback sin formato si no es 7 u 8 dígitos
    END IF;

    RETURN formatted || '-' || UPPER(dv);
END;
$function$
;

alter table curriculums
    alter column experience type text;

ALTER TABLE bdt_offers ALTER COLUMN offer_location DROP NOT NULL;

ALTER TABLE curriculums RENAME COLUMN referrals TO referals;
