-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

CREATE TYPE "offerapplicationstatus" AS ENUM (
    'ACCEPTED',
    'DENIED',
    'NEEDS_REVIEW',
    'UNSEEN');

CREATE TYPE "utemroles" AS ENUM (
    'ROLE_ADMINISTRATOR',
    'ROLE_COMPANY',
    'ROLE_USER');

CREATE TYPE "workmode" AS ENUM (
    'FLEXIBLE',
    'PRESENTIAL_ONLY',
    'REMOTE_ONLY');

CREATE TYPE "worktype" AS ENUM (
    'FULL_TIME',
    'INTERNSHIP',
    'PART_TIME');

CREATE SEQUENCE app_users_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE bdt_offers_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE experience_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE offer_applications_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE offer_locations_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE TABLE companies
(
    digito_verificador varchar(1)   NOT NULL,
    rut                int4         NOT NULL,
    created_at         timestamp(6) NOT NULL,
    updated_at         timestamp(6) NOT NULL,
    fantasy_name       varchar(255) NOT NULL,
    CONSTRAINT companies_pkey PRIMARY KEY (rut)
);

CREATE TABLE offer_locations
(
    created_at     timestamp(6)                                                                                                             NOT NULL,
    id             int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    updated_at     timestamp(6)                                                                                                             NOT NULL,
    address        varchar(255)                                                                                                             NULL,
    address_number varchar(255)                                                                                                             NULL,
    city           varchar(255)                                                                                                             NOT NULL,
    district       varchar(255)                                                                                                             NOT NULL,
    region         varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT offer_locations_pkey PRIMARY KEY (id)
);

CREATE TABLE app_users
(
    associated_company int4                                                                                                                     NULL,
    digito_verificador varchar(1)                                                                                                               NOT NULL,
    rut                int4                                                                                                                     NOT NULL,
    created_at         timestamp(6)                                                                                                             NOT NULL,
    id                 int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    updated_at         timestamp(6)                                                                                                             NOT NULL,
    email              varchar(255)                                                                                                             NOT NULL,
    lastname           varchar(255)                                                                                                             NULL,
    "name"             varchar(255)                                                                                                             NOT NULL,
    "password"         varchar(255)                                                                                                             NOT NULL,
    "role"             "utemroles"                                                                                                       NOT NULL,
    CONSTRAINT app_users_email_key UNIQUE (email),
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_rut_key UNIQUE (rut),
    CONSTRAINT fknyprwycfavxfshfa58tv0we7n FOREIGN KEY (associated_company) REFERENCES companies (rut)
);

CREATE TABLE bdt_offers
(
    salary            float8                                                                                                                   NOT NULL,
    created_at        timestamp(6)                                                                                                             NOT NULL,
    end_date          timestamp(6)                                                                                                             NOT NULL,
    id                int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    offer_author      int8                                                                                                                     NULL,
    offer_location    int8                                                                                                                     NOT NULL,
    start_date        timestamp(6)                                                                                                             NOT NULL,
    updated_at        timestamp(6)                                                                                                             NOT NULL,
    offer_description varchar(255)                                                                                                             NOT NULL,
    offer_name        varchar(255)                                                                                                             NOT NULL,
    work_mode         "workmode"                                                                                                        NOT NULL,
    work_type         "worktype"                                                                                                        NOT NULL,
    CONSTRAINT bdt_offers_pkey PRIMARY KEY (id),
    CONSTRAINT fkj30g8mhw49ddc6gcpo46yagbv FOREIGN KEY (offer_location) REFERENCES offer_locations (id),
    CONSTRAINT fkkuy7jt9gramvqnper4cb9cl38 FOREIGN KEY (offer_author) REFERENCES app_users (id)
);

CREATE TABLE experience
(
    app_user     int8                                                                                                                     NOT NULL,
    created_at   timestamp(6)                                                                                                             NOT NULL,
    end_date     timestamp(6)                                                                                                             NULL,
    id           int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    start_date   timestamp(6)                                                                                                             NOT NULL,
    updated_at   timestamp(6)                                                                                                             NOT NULL,
    company_name varchar(255)                                                                                                             NOT NULL,
    description  varchar(255)                                                                                                             NULL,
    title        varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT experience_pkey PRIMARY KEY (id),
    CONSTRAINT fk2uxaag389ieoqpqfpwwtg4ols FOREIGN KEY (app_user) REFERENCES app_users (id)
);

CREATE TABLE offer_applications
(
    appliant_user            int8                                                                                                                     NOT NULL,
    application_request_date timestamp(6)                                                                                                             NOT NULL,
    created_at               timestamp(6)                                                                                                             NOT NULL,
    id                       int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    offer                    int8                                                                                                                     NOT NULL,
    updated_at               timestamp(6)                                                                                                             NOT NULL,
    application_status       "offerapplicationstatus"                                                                                          NOT NULL,
    CONSTRAINT offer_applications_pkey PRIMARY KEY (id),
    CONSTRAINT fkcgfrlxdfy09qcj3akq0w3upr3 FOREIGN KEY (offer) REFERENCES bdt_offers (id),
    CONSTRAINT fkjdxtir0u5405xi3w7d2hmp0xh FOREIGN KEY (appliant_user) REFERENCES app_users (id)
);